class OrderStatus:
    DELAYED = 'DELAYED'
    INVESTIGATING = 'INVESTIGATING'
    FOLLOWING_UP = 'FOLLOWING_UP'
    DONE = 'DONE'
    OPEN = 'OPEN'

class TripStatus:
    DELIVERED = 'DELIVERED'
    PICKED = 'PICKED'
    AT_VENDOR = 'AT_VENDOR'
    ASSIGNED = 'ASSIGNED'